version: 2

jobs:
    build:
        docker:
            - image: cyclus/cyclus-deps
        working_directory: ~/cyclus
        steps:
            - checkout
            - run:
                name: Build Docker Image
                command: |
                    python install.py -j 2 --build-type=Release --core-version 999999.999999 \
                    -DBLAS_LIBRARIES="/opt/conda/lib/libblas.so" \
                    -DLAPACK_LIBRARIES="/opt/conda/lib/liblapack.so"
            - run:
                name: save SHA to a file
                command: echo $CIRCLE_SHA1 > .circle-sha
            - save_cache:
                key: v1-repo-{{ checksum ".circle-sha" }}
                paths:
                  - /root

    deploy_latest:
        docker:
            - image: circleci/ruby:2.4-node
        working_directory: ~/cyclus
        steps:
            - checkout
            - run:
                name: Place the proper Dockerfile
                command: cp docker/cyclus-ci/Dockerfile .
            - setup_remote_docker
            - run:
                name: log into Docker
                command: |
                    docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            - run:
                name: Build Docker container
                command: docker build --rm=false -t cyclus/cyclus:latest .
            - run:
                name: Push on DockerHub
                command: docker push cyclus/cyclus:latest # push to docker depot

    deploy_stable:
        docker:
            - image: circleci/ruby:2.4-node
        working_directory: ~/cyclus
        steps:
            - checkout
            - run:
                name: Place the proper Dockerfile
                command: cp docker/cyclus-ci/Dockerfile .
            - setup_remote_docker
            - run:
                name: Log on DockerHub
                command: |
                  docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            - run:
                name: Tag and Push on DockerHub
                command: |
                  docker tag cyclus/cyclus:latest cyclus/cyclus:stable # creation
                  docker push cyclus/cyclus:stable # push to docker depot

    deb_generation:
        docker:
            - image: circleci/ruby:2.4-node
        working_directory: ~/cyclus
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Tag and Push on DockerHub
                command: |
                  docker/deb-ci/build_upload_deb.sh 14
                  docker/deb-ci/build_upload_deb.sh 16
    
    empty_test:
        machine: true
        steps:
            - run:
                name: Cycamore/Cymetric tests
                no_output_timeout: "20m"
                command: |
                  # Install circleci 
                  mkdir ./bin
                  curl -o ./bin/circleci https://raw.githubusercontent.com/rockymadden/circleci-cli/master/src/circleci 
                  chmod 755 ./bin/circleci

                  build_num=`curl --user ${CYCAMORE_CIRCLE_TOKEN}: \
                  --data build_parameters[CIRCLE_JOB]=empty_test \
                  https://circleci.com/api/v1.1/project/github/cyclus/cycamore/tree/ci-test | \
                  grep build_num | cut -d":" -f2 |cut -d"," -f1 | tail -n 2 | head -n 1`
                  build_num="$(echo -e "${build_num}" | tr -d '[:space:]')"
                  echo "Build_num: ${build_num}"
                  echo "./bin/circleci await cyclus/cycamore ${build_num#0} |grep \"outcome\" |cut -d"\"" -f4"
                  ./bin/circleci await cyclus/cycamore 435 -r 30
                  job_name=`./bin/circleci await cyclus/cycamore 435 |grep \"outcome\" |cut -d"\"" -f4`
                  if [[ "$job_name" == "success" ]] ; then
                    exit 0;
                  else 
                    exit 1;
                  fi


    test_cycamore:
        machine: true
        steps:
            - run:
                name: Cycamore/Cymetric 
                command: |
                  # Install circleci 
                  mkdir ./bin
                  curl -o ./bin/circleci https://raw.githubusercontent.com/rockymadden/circleci-cli/master/src/circleci 
                  chmod 755 ./bin/circleci

                  # Trigger the project
                  ./bin/circleci init --token $CYCAMORE_CIRCLE_TOKEN
                  ./bin/circleci trigger cyclus/cycamore develop
                  job_name=`./bin/circleci await cyclus/cycamore |grep outcome |cut -d"\"" -f4`
                  if [[ "$job_name" == "success" ]] ; then
                    exit 0;
                  else 
                    exit 1;
                  fi
                no_output_timeout: "20m"
    test_cymetric:
        machine: true
        steps:
            - run:
                name: Cycamore/Cymetric tests
                command: |
                  # Install dependencies
                  mkdir ./bin
                  curl -o ./bin/circleci https://raw.githubusercontent.com/rockymadden/circleci-cli/master/src/circleci 
                  chmod 755 ./bin/circleci

                  # Trigger the project
                  ./bin/circleci init --token $CYMETRIC_CIRCLE_TOKEN
                  ./bin/circleci trigger cyclus/cymetric develop
                  job_name=`./bin/circleci await cyclus/cymetric |grep outcome |cut -d"\"" -f4`
                  if [[ "$job_name" == "success" ]] ; then
                    exit 0;
                  else 
                    exit 1;
                  fi
                no_output_timeout: "20m"

    unit_test:
        docker:
            - image: cyclus/cyclus-deps
        working_directory: ~/root
        steps:
            - run:
                name: save SHA to a file
                command: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                  - v1-repo-{{ checksum ".circle-sha" }}
            - run:
                name: Unit Test
                command: /root/.local/bin/cyclus_unit_tests; exit $?
    nosetest:
        docker:
            - image: cyclus/cyclus-deps
        working_directory: ~/root
        steps:
            - run:
                name: save SHA to a file
                command: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                  - v1-repo-{{ checksum ".circle-sha" }}
            - run:
                name: Install nosetest
                command: pip install nose
            - run:
                name: Nosetest
                command: nosetests -w ~/cyclus/tests; exit $?

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - empty_test
            - unit_test:
                requires:
                    - build
            - nosetest:
                requires:
                    - build
            
            - deploy_latest:
                filters:
                    branches:
                        only: develop
                requires:
                    - unit_test
                    - nosetest

            - deploy_stable:
                filters:
                    branches:
                        only: master
                requires:
                    - unit_test
                    - nosetest

            - test_cycamore:
                requires:
                    - unit_test
                    - nosetest
            - test_cymetric:
                requires:
                    - unit_test
                    - nosetest
                    - test_cycamore

            - deb_generation:
                filters:
                    branches:
                        only: master
                requires:
                    - unit_test
                    - nosetest
