name: Build & Test PR

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'docker/Dockerfile'
      - '.github/workflows/docker_publish.yml'

jobs:
  build-dependency-and-test-img:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ubuntu_versions : [
          22.04,
          ]
        pkg_mgr : [
          apt,
          conda,
        ]

    name: Installing Dependencies, Building cyclus and running tests
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installing Dependencies in Docker image
        uses: firehed/multistage-docker-build-action@v1
        with:
          repository: ghcr.io/${{ github.repository_owner }}/cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}
          stages: ${{ matrix.pkg_mgr }}-deps, cyclus
          server-stage: cyclus-test
          quiet: false
          parallel: true
          tag-latest-on-default: false
          dockerfile: docker/Dockerfile
          build-args: pkg_mgr=${{ matrix.pkg_mgr }}
