name: Build/Test for PR and collaborator push

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/workflows/build_test_publish.yml'
      - '.github/workflows/changelog_test.yml'
      - 'docker/**'
      - 'doc/**'
  push:
    paths-ignore:
      - '.github/workflows/build_test_publish.yml'
      - '.github/workflows/changelog_test.yml'
      - 'docker/**'
      - 'doc/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ubuntu_versions : [
          20.04,
          22.04,
          ]
        pkg_mgr : [
            apt,
            conda
        ]
    
    container:
      image: ghcr.io/cyclus/cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/${{ matrix.pkg_mgr }}-deps

    steps:
      - name: Checkout and Build Cyclus
        uses: actions/checkout@v3

      - name: echo some stuff
        run: |
          python -m site --user-site
          ls /github/home/.local/lib/python3.8/site-packages

      - name: Building Cyclus
        run: |
          mkdir `python -m site --user-site`
          python install.py -j 2 --build-type=Release --core-version 999999.999999 
          echo "PATH=${HOME}/.local/bin:$PATH" >> "$GITHUB_ENV"
          echo "LD_LIBRARY_PATH=${HOME}/.local/lib:${HOME}/.local/lib/cyclus:$LD_LIBRARY_PATH" >> "$GITHUB_ENV"

      - name: Cyclus Unit Tests
        run: |
          cyclus_unit_tests

      - name: Cyclus Python Tests
        run: |
          cd tests && python -m pytest --ignore test_main.py
