name: Build & Publish docker image for CI

on:
  # allows us to run workflows manually
  workflow_dispatch:
  push:
    paths:
      - 'docker/Dockerfile'
      - '.github/workflows/docker_publish.yml'

jobs:
  build-dependency-and-test-img:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ubuntu_versions : [
          22.04,
          ]
        pkg_mgr : [
          apt,
          conda,
        ]

    name: Installing Dependencies, Building cyclus and running tests
    steps:
      - name: default environment
        run: |
          echo "tag-latest-on-default=false" >> "$GITHUB_ENV"

      - name: condition on trigger parameters
        if: ${{ github.repository_owner == 'svalinn' && github.ref == 'refs/heads/develop' }}
        run: |
          echo "tag-latest-on-default=true" >> "$GITHUB_ENV"

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installing Dependencies in Docker image
        uses: firehed/multistage-docker-build-action@v1
        with:
          repository: ghcr.io/${{ github.repository_owner }}/cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}
          stages: ${{ matrix.pkg_mgr }}-deps
          server-stage: cyclus
          quiet: false
          parallel: true
          tag-latest-on-default: ${{ env.tag-latest-on-default }}
          dockerfile: docker/Dockerfile
          build-args: pkg_mgr=${{ matrix.pkg_mgr }}


  push_stable_ci_img:
    needs: [build-dependency-and-test-img]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ubuntu_versions : [
          22.04,
          ]
        pkg_mgr : [
          apt,
          conda,
          ]
  
    name: Pushing final images
    steps:       
      - name: Log in to the Container registry
        if: ${{ github.repository_owner == 'cyclus' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Store image name
        if: ${{ github.repository_owner == 'cyclus' }}
        run: |
          echo "image_base_tag=ghcr.io/${{ github.repository_owner }}/cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}" >> "$GITHUB_ENV"

      - name: Push Image as latest img
        if: ${{ github.repository_owner == 'cyclus' && github.ref == 'refs/heads/develop' }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ${{ env.image_base_tag }}/cyclus:latest
          dst: ${{ env.image_base_tag }}:latest

      - name: Push Image as latest img
        if: ${{ github.repository_owner == 'cyclus' && github.ref == 'refs/heads/develop' }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ${{ env.image_base_tag }}:latest
          dst: ${{ env.image_base_tag }}:stable
